spring:
  datasource:
#   数据源基本配置
    username: root
    password: egova
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medicineapp?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    date-format: yyyy-MM-dd
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    freemarker:
  freemarker:
    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8
    password: egovaredis

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
server:
  context-path: /medicineapp
